"""empty message

Revision ID: 04554633e1f4
Revises: 7d9ba718b4ae
Create Date: 2026-02-09 00:50:14.171119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04554633e1f4'
down_revision = '7d9ba718b4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petcomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petcomment')
    # ### end Alembic commands ###
