"""empty message

Revision ID: 160158990e11
Revises: 86ab67dcd125
Create Date: 2026-02-05 09:10:28.066379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160158990e11'
down_revision = '86ab67dcd125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill')
    # ### end Alembic commands ###
