"""empty message

Revision ID: 21c1f61f813a
Revises: 7d9ba718b4ae
Create Date: 2026-02-09 17:03:17.536129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c1f61f813a'
down_revision = '7d9ba718b4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitterskills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sitter_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sitter_id'], ['sitter.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitterskills')
    # ### end Alembic commands ###
