"""empty message

Revision ID: 3d5fc617e701
Revises: 53bb03468623
Create Date: 2026-02-02 23:43:56.819544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5fc617e701'
down_revision = '53bb03468623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm_password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitter', schema=None) as batch_op:
        batch_op.drop_column('confirm_password')

    # ### end Alembic commands ###
