"""empty message

Revision ID: 55851d6b8422
Revises: c94e056b6b12
Create Date: 2026-02-13 10:57:14.597469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55851d6b8422'
down_revision = 'c94e056b6b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useradmin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useradmin')
    # ### end Alembic commands ###
