"""empty message

Revision ID: 71d53ca292e0
Revises: dbd02944425c
Create Date: 2026-02-24 22:30:13.050611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71d53ca292e0'
down_revision = 'dbd02944425c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_sitter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('applied', 'selected', 'rejected', 'withdrawn', name='application_status'), nullable=False))
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_sitter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', postgresql.ENUM('applied', 'selected', 'rejected', 'withdrawn', name='application_state'), autoincrement=False, nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
