"""empty message

Revision ID: 7eddaea5733f
Revises: 1133da9d3de6
Create Date: 2026-02-02 11:22:38.036790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eddaea5733f'
down_revision = '1133da9d3de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
