"""empty message

Revision ID: 880b9b047240
Revises: a7ba7b8c06a9
Create Date: 2026-02-05 16:06:09.881675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880b9b047240'
down_revision = 'a7ba7b8c06a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('nie',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('sterilized',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('sterilized',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('nie',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
