"""remove confirm_password from sitter

Revision ID: 927ab48e86f8
Revises: 385eb03a641f
Create Date: 2026-02-13 13:25:09.611683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927ab48e86f8'
down_revision = '385eb03a641f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitter', schema=None) as batch_op:
        batch_op.drop_column('confirm_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm_password', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
