"""empty message

Revision ID: b9094827b701
Revises: 04554633e1f4
Create Date: 2026-02-10 00:36:08.210411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9094827b701'
down_revision = '04554633e1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petcomment')
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_pet', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('about_pet')

    op.create_table('petcomment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], name=op.f('petcomment_pet_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('petcomment_pkey'))
    )
    # ### end Alembic commands ###
